# values.yaml
replicaCount: 1

image:
  pullPolicy: Always
  repository: 637423357038.dkr.ecr.us-east-2.amazonaws.com/rollback-poc
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

#serviceAccount:
#  create: true
#  name:

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

istio:
  enabled: true
  gateway:
    enabled: true
    name: my-gateway
  virtualService:
    enabled: true
    name: my-virtual-service

